---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: suyash
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "suyash1910/calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker service
      service:
        name: docker
        state: started

    # - name: Remove old container
    #   shell: docker rm -f calculator

    - name: Remove old container if it exists
      docker_container:
        name: calculator
        state: absent

    - name: Running container
      docker_container:
        name: calculator
        image: suyash1910/calculator:latest
        state: started
        # detach: true
        # tty: true
      
    # - name: Running container
    #   shell: docker run -it -d --name calculator suyash1910/calculator:latest